### PR TITLE
refactor(ndt_omp): prefix with autoware_

### PR DESCRIPTION
**Pull request by esteve**
This PR prefixes `ndt_omp` with `autoware_`

See https://github.com/autowarefoundation/autoware/issues/4569

### CODE REVIEW

**Comment by esteve** [comment]
@SakodaShintaro can you review this PR when you have a moment? Thanks.

**Comment by SakodaShintaro** [comment]
Thank you for the pull request.
The corresponding pull requests for autoware.universe and localization_evaluation_tools (a private TIER IV repository) need to be prepared. I will create these, so please wait one or two days.

**Comment by SakodaShintaro** [comment]
@esteve 
Sorry, but the situation is a bit complicated as to whether or not to add "autoware_" prefix to ndt_omp, so please consult with @mitsudome-r -san

**Comment by esteve** [comment]
@SakodaShintaro I spoke about this with @mitsudome-r and @xmfcx yesterday during the ASWG meeting and they were ok with adding the prefix to `ndt_omp`. Moreover, we agreed a while ago that any public change shouldn't be blocked by the private development of TierIV or any other company.

**Comment by mitsudome-r** [comment]
@esteve I had a discussion with TIER IV localization team regarding the naming. First of all, they are okay with adding autoware_ prefix to the package. However, they were a bit worried about having a similar package registered to ROS Buildfarm with just adding a prefix to the package.
 
Are there any examples where there is a forked package released as a binary with a different name in ROS Buildfarm?
Also, since the package is just a library used for ndt_scan_matcher, they were also wondering if there is a way to just statically link this library within ndt_scan_matcher and not release this package as binary if it isn't a good thing to release pretty much the duplicate of existing package.

**Comment by SakodaShintaro** [comment]
I think that one option could be to abandon this repository and move all the necessary code into the `ndt_scan_matcher` package in autoware.universe. What do you think about this approach?

**Comment by esteve** [comment]
AFAIK the only package that depends on `ndt_omp` is `ndt_scan_matcher`, so we could just roll all the code here into that package and not worry about existing packages in the ROS index.

**Comment by esteve** [comment]
@SakodaShintaro I can move the code from here to `ndt_scan_matcher`, but I'd prefer to do it when this repository is archived, to prevent anyone from pushing new commits. Thanks.

**Comment by SakodaShintaro** [comment]
There are no particular changes we want to make in the near future in this repository, so I think it will be fine to proceed with the archive and move flow. I will discuss this with the team.  

Additionally, there is currently a pull request on autoware.universe to add a prefix to `ndt_scan_matcher`, so I would like to handle that first:  
https://github.com/autowarefoundation/autoware.universe/pull/8904  
I think I will be able to get it done by tomorrow.

**Comment by mitsudome-r** [comment]
@SakodaShintaro Thanks!

**Comment by SakodaShintaro** [comment]
I created a pull request in autoware.universe to visualize the necessary changes:  
https://github.com/autowarefoundation/autoware.universe/pull/8912  
Based on this PR, after confirming that there are no objections, I will archive the ndt_omp repository and finalize the PR in autoware.universe.

**Comment by SakodaShintaro** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/8912 has been merged.

**Pull request closed without merging**
