### PR TITLE
Support general SIMD instruction

### PR DESCRIPTION
**Pull request by KeisukeShima**
Rebased #8

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Why did you re-create a PR? :thinking:

**Comment by KeisukeShima** [comment]
@kenji-miyake Because this repository rejected force push.

**Comment by kenji-miyake** [comment]
I could do that, so I'm sorry but I'll close this.
image

**Comment by KeisukeShima** [comment]
Ok, thanks! Maybe you have a permission.

**Pull request closed without merging**
