### PR TITLE
chore: add pre-commit to apply clang-format automatically

### PR DESCRIPTION
**Pull request by SakodaShintaro**
Added pre-commit

### CODE REVIEW

**Comment by SakodaShintaro** [comment]
@anhnv3991 
I created GitHub Actions to automatically apply formatters before reviewing your pull request. 
Could you please review it?

**Comment by anhnv3991** [comment]
> @anhnv3991 I created GitHub Actions to automatically apply formatters before reviewing your pull request. Could you please review it?

@SakodaShintaro The changes seem OK but how can I test them locally/remotely?

**Comment by SakodaShintaro** [comment]
@anhnv3991 
Thanks!
I don't know how to properly test GitHub actions, so there's no need to test anything.
If the code seems okay, please approve.

**Review by anhnv3991 — APPROVED** [review]
LGTM

**Pull request merged**
