### PR TITLE
feat: merge map change checker features to the main branch

### PR DESCRIPTION
**Pull request by anhnv3991**
## Description
- Merge the all branches related to map change checker to the tier4/main branch

## How to test
- Test together with [this PR](https://github.com/tier4/map_assessment_tools/pull/27)
- Need to test with Autoware logging simulator.

### CODE REVIEW

**Comment by SakodaShintaro** [comment]
For some reason, the CI checks failed. I will investigate.

**Comment by SakodaShintaro** [comment]
I was able to reproduce the error. Currently, pull requests from forked repositories may fail during CI checks.
https://github.com/tier4/ndt_omp/pull/62

**Comment by SakodaShintaro** [comment]
@anhnv3991 
~~Sorry, could you push the branch to tier4/ndt_omp repository and recreate pull request from the branch?~~

I might have found a way to fix it. https://github.com/tier4/ndt_omp/pull/62/commits/4fecf84ca8534514bc623afc66f5507b5b4013be

**Comment by SakodaShintaro** [comment]
@anhnv3991 
Unfortunately, `pre-commit` failed.
Could you apply formatter(clang-format) to `include/multigrid_pclomp/multigrid_ndt_omp.h`?

If you use VSCode, the following extension is useful.

image

**Comment by anhnv3991** [comment]
@SakodaShintaro I just used xargs clang-format-14. Which version is used for this pipeline?

**Comment by SakodaShintaro** [comment]
I use 
```
$ clang-format --version
clang-format version 17.0.5 (https://github.com/ssciwr/clang-format-wheel 1fc815404015575a1c0c40c1994b7522ab89fe86)
```

But this PR's difference about formatting may come from `.clang-format`. It is updated in https://github.com/tier4/ndt_omp/pull/58, I think this PR's formatting style may be old one.

**Review by SakodaShintaro — APPROVED** [review]
`pclomp/*` is not currently used in autoware, so this pull request does not affect its operation. I have confirmed that `logging_simulator` etc. works properly.
In the future, it may be a good idea to remove these files from this repository and move them to `map_assessment_tools`.
LGTM

**Pull request merged**
