### PR TITLE
fix(ndt_omp): disable line search

### PR DESCRIPTION
**Pull request by YamatoAndo**
Signed-off-by: YamatoAndo <yamato.ando@gmail.com>

disable line search

### CODE REVIEW

**Comment by wadexu** [comment]
May i know the reason to disable the line search? Thank you

**Comment by YamatoAndo** [comment]
@wadexu 
This is because the convergence condition was sometimes met in the middle of the process and converged to the wrong position.

**Comment by wadexu** [comment]
> @wadexu This is because the convergence condition was sometimes met in the middle of the process and converged to the wrong position.

Got it. Thanks. What could be the root cause? I think the line search itself should not be the root cause.

**Comment by YamatoAndo** [comment]
I think the root cause is that when the line search is performed near the local solution, the convergence condition of NDT Scan Matcihng is satisfied.

This PR (https://github.com/tier4/ndt_omp/pull/15) is trying to solve the root cause.
But he said there is still some problems, and he is working on it.

**Comment by YamatoAndo** [comment]
Since I've created a new [pull request](https://github.com/tier4/ndt_omp/pull/21), I will close this one.

**Pull request closed without merging**
