### PR TITLE
add compile flag to change compile options

### PR DESCRIPTION
**Pull request by KeisukeShima**
Added compiler flags to avoid problems related to optimization flags when generating binaries on the server.

Related link:
https://star4.slack.com/archives/C017VB9UG1L/p1647489698477679
https://github.com/koide3/ndt_omp/pull/44#issuecomment-1019079452

Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>

### CODE REVIEW

**Comment by harihitode** [comment]
Thank you @KeisukeShima .
This PR should be merged after merging [this PR](https://github.com/autowarefoundation/autoware.universe/pull/577) in universe. 

Is it better to change the hash in [autoware.repos](https://github.com/autowarefoundation/autoware/blob/4245f9c51a7f792680a4a066c20bf5631171c423/autoware.repos#L32) ? Do you have any idea?

**Comment by harihitode** [comment]
> Thank you @KeisukeShima . This PR should be merged after merging [this PR](https://github.com/autowarefoundation/autoware.universe/pull/577) in universe.
> 
> Is it better to change the hash in [autoware.repos](https://github.com/autowarefoundation/autoware/blob/4245f9c51a7f792680a4a066c20bf5631171c423/autoware.repos#L32) ? Do you have any idea?

**Comment by harihitode** [comment]
This PR and [universe's one](https://github.com/autowarefoundation/autoware.universe/pull/577) have to be synchronized.

If not, these changes cause segfaults at startup of autoware. 

@kenji-miyake, @KeisukeShima

**Comment by KeisukeShima** [comment]
@harihitode Thanks for managing this PR!

> Thank you @KeisukeShima . This PR should be merged after merging [this PR](https://github.com/autowarefoundation/autoware.universe/pull/577) in universe.
> 
> Is it better to change the hash in [autoware.repos](https://github.com/autowarefoundation/autoware/blob/4245f9c51a7f792680a4a066c20bf5631171c423/autoware.repos#L32) ? Do you have any idea?

Since the `tier4/main` branch has already been specified as version, you do not need to do anything.
When this PR is merged, the hash referenced by autoware will also be updated.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
